# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-22.04"
CLUSTER_NAME = "LOCAL-SERVER"
VM_IP_PREFIX = "10.12.0."
VM_IP_START = 100 
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  # VM Basic Settings
  config.vm.box = "#{BOX_IMAGE}"
  config.vm.box_check_update = false

  (1..NODE_COUNT).each do |i|
    config.vm.define "#{CLUSTER_NAME}-0#{i}" do |node|
      # Hostname
      node.vm.hostname = "#{CLUSTER_NAME}-0#{i}"

      # Network
      node.vm.network :private_network, ip: "#{VM_IP_PREFIX}#{i + VM_IP_START}"

      # Forward Port
      # config.vm.network "forwarded_port", guest: 2375, host: "#{i}" + "2375"

      # VM
      node.vm.provider "virtualbox" do |vb|
          vb.cpus = 2
          vb.memory = 4096 
          vb.name = "#{CLUSTER_NAME}-0#{i}"
      end


      node.vm.provision "install_tools", type: "shell",  path: "../scripts/install_tools.sh" 

      node.vm.provision "install_docker", type: "shell",  path: "../scripts/install_docker.sh" 

      node.vm.provision "install_exporters", type: "shell",  path: "../scripts/install_exporters.sh" 

      node.vm.provision "install_zookeeper", 
      env: {
          "ZOO_MY_ID" => i, 
      },
      type: "shell",  path: "../scripts/install_zookeeper.sh" 

      if i == 1
        node.vm.provision "install_prometheus", type: "shell",  path: "../scripts/install_prometheus.sh" 
        node.vm.provision "install_nginx", type: "shell",  path: "../scripts/install_nginx.sh" 
      end
    end
  end
end
