# -*- mode: ruby -*-
# vi: set ft=ruby :

HOST_NAME = "dev-server"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = $HOST_NAME
  config.vm.define "#{HOST_NAME}" do |t|
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "10.12.26.100"

  config.vm.provider "virtualbox" do |vb|
    vb.name = $HOST_NAME 
    vb.cpus = "4"
    vb.memory = "4096"
  end

  config.vm.provision "install_tools", type: "shell",  path: "../scripts/install_tools.sh" 

  config.vm.provision "install_docker", type: "shell",  path: "../scripts/install_docker.sh" 
  config.vm.provision "install_golang", type: "shell",  path: "../scripts/install_golang.sh" 

end
